package com.vulnerabilidade.enumeration;

public enum Genero {
  
  FEMININO, MASCULINO, 
  CISGÊNERO, TRANSGÊNERO,
  NÃO_BINÁRIO, AGÊNERO,
  GÊNERO_FLUIDO, ARROMÂNTICO,
  TRANSEXUAL, PANGÊNERO,
  QUEER, TWO_SPIRIT,
  TERCEIRO_GÊNERO, INTERGÊNERO,
  ALIADO, BIGÊNERO,
  DEMIGÊNERO, ANDRÓGINA, 
  GÊNERO_NEUTRO, FEMME,
  BUTCH, MAVERIQUE,
  ALIAGÊNERO
  
}
